version: 2.1
executors:
  build-executor:
    docker:
      - image: circleci/node:10
    working_directory: ~/immerge-website

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - test-e2e:
          requires:
            - build
      - deploy:
          requires:
            - test
            - test-e2e
          filters:
            branches:
              only: master

jobs:
  test:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/immerge-website
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run Tests
          command: yarn run test --no-watch --no-progress --browsers=ChromeHeadlessCI

  test-e2e:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/immerge-website
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run Tests
          command: yarn run e2e --protractor-config=e2e/protractor-ci.conf.js

  build:
    executor: build-executor
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: linting angular project
          command: yarn run lint
      - run:
          name: build angular project
          command: yarn run build --prod
      - persist_to_workspace:
          root: workspace
          paths:
            - echo-output
  
  deploy:
    executor: build-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: deploy to firebase hosting
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
